

--What is the total revenue generated by male vs female customers?
SELECT gender, SUM(puchase_amount) as revenue
FROM customer_behavior
GROUP BY gender

--Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, puchase_amount 
from customer_behavior
WHERE discount_applied = 'Yes' AND puchase_amount>= (SELECT AVG(puchase_amount) FROM customer_behavior)

--Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) as 'average product rating' 
FROM customer_behavior
group by item_purchased
order by AVG(review_rating) DESC


--Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type,
ROUND(AVG(puchase_amount),2)
from customer_behavior
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
ROUND(COUNT(customer_id),2) AS total_customers,
ROUND(AVG(puchase_amount),2) as avg_spend,
SUM(puchase_amount) as total_revenue
FROM customer_behavior
GROUP BY  subscription_status
ORDER BY total_revenue, avg_spend DESC;

--Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)/COUNT(*),2) as diScount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC


--Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_behavior
)
SELECT customer_segment, COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;



--what are the top 3 most purchased products within each category
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;
--Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status
--What is the revenue contribution of each group
SELECT age_group,
SUM(puchase_amount) as total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue desc;
